# -*- coding: utf-8 -*-
"""html_quick_styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8u2_KFxO5EPUGGZeFLbt2TNllXFs4dd
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

# ============================================================================
# HTML QUICK-STYLER - WITH PROPER CONTAINERS
# ============================================================================

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        """Generate a cohesive color palette based on style"""

        palettes = {
            'modern': {
                'primary': '#2c3e50',
                'secondary': '#34495e',
                'accent': '#3498db',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'vibrant': {
                'primary': '#27ae60',
                'secondary': '#1e8449',
                'accent': '#52be80',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'ocean': {
                'primary': '#0099cc',
                'secondary': '#006699',
                'accent': '#00ccff',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'forest': {
                'primary': '#2ecc71',
                'secondary': '#27ae60',
                'accent': '#f1c40f',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'sunset': {
                'primary': '#ff8c42',
                'secondary': '#ff6b35',
                'accent': '#ffa751',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'luxury': {
                'primary': '#1a1a2e',
                'secondary': '#16213e',
                'accent': '#e94560',
                'background': '#0a0a0f',
                'surface': '#1e1e2e',
                'text_primary': '#f1f5f9',
                'text_secondary': '#a0a0b0',
                'border': '#2a2a3a'
            },
            'creative': {
                'primary': '#667eea',
                'secondary': '#764ba2',
                'accent': '#f093fb',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'minimal': {
                'primary': '#9b59b6',
                'secondary': '#8e44ad',
                'accent': '#e74c3c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            }
        }

        return palettes.get(style.lower(), palettes['modern'])

    @staticmethod
    def get_color_preview_html(palette: Dict[str, str]) -> str:
        """Generate simple HTML for color palette preview"""

        preview_html = """
        <div style="font-family: 'Inter', sans-serif; background: #1a1a2e; padding: 25px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.3); margin: 20px 0;">

            <!-- Simple Header -->
            <div style="text-align: center; margin-bottom: 25px;">
                <h3 style="color: #fff; font-size: 24px; font-weight: 600; margin: 0;">Color Palette</h3>
                <p style="color: #94a3b8; font-size: 14px; margin-top: 8px;">DISCOVER YOUR PERFECT PALETTE</p>
            </div>

            <!-- Color Grid -->
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px;">
        """

        # Add each color
        for color_name, color_code in palette.items():
            # Determine text color based on background brightness
            def get_text_color(hex_color):
                hex_color = hex_color.lstrip('#')
                r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
                brightness = (r * 299 + g * 587 + b * 114) / 1000
                return '#000000' if brightness > 128 else '#ffffff'

            text_color = get_text_color(color_code)

            preview_html += f"""
                <div style="background: {color_code}; border-radius: 12px; padding: 15px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.2);">
                    <div style="width: 100%; height: 60px; background: {color_code}; border-radius: 8px; margin-bottom: 10px; border: 2px solid rgba(255,255,255,0.2);"></div>
                    <div style="color: {text_color}; font-weight: 600; font-size: 13px; text-transform: uppercase; margin-bottom: 5px;">{color_name.replace('_', ' ')}</div>
                    <div style="color: {text_color}; font-family: monospace; font-size: 12px; background: rgba(0,0,0,0.2); padding: 4px 8px; border-radius: 4px; display: inline-block;">{color_code}</div>
                </div>
            """

        preview_html += """
            </div>
        </div>
        """

        return preview_html

class HTMLPageBuilder:
    """Build styled HTML pages from descriptions"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        """Extract sections from description"""
        sections = []

        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }

        desc_lower = description.lower()

        for section_type, keywords in section_keywords.items():
            for keyword in keywords:
                if keyword in desc_lower:
                    sections.append(section_type)
                    break

        if not sections:
            sections = ['hero', 'features', 'contact', 'footer']

        return sections

    @staticmethod
    def generate_meta_tags(title: str, description: str) -> str:
        """Generate SEO meta tags"""
        meta_tags = f'''    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description[:160]}">
    <meta name="theme-color" content="#0f172a">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description[:160]}">
    <meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="author" content="HTML Quick-Styler">'''
        return meta_tags

    @staticmethod
    def generate_section_html(section_type: str, palette: Dict) -> str:
        """Generate HTML for specific section with proper containers"""

        sections = {
            'hero': f'''        <section class="hero-section">
            <div class="container">
                <div class="hero-content">
                    <h1>Welcome to Your Site</h1>
                    <p>Create amazing web experiences</p>
                    <button class="btn btn-primary">Get Started</button>
                </div>
            </div>
        </section>''',

            'features': f'''        <section class="features-section">
            <div class="container">
                <h2 class="section-title">Features</h2>
                <div class="features-grid">
                    <div class="feature-card">
                        <div class="feature-icon">⚡</div>
                        <h3>Fast</h3>
                        <p>Lightning-quick performance</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">🔒</div>
                        <h3>Secure</h3>
                        <p>Enterprise-grade security</p>
                    </div>
                    <div class="feature-card">
                        <div class="feature-icon">📈</div>
                        <h3>Scalable</h3>
                        <p>Grow without limits</p>
                    </div>
                </div>
            </div>
        </section>''',

            'about': f'''        <section class="about-section">
            <div class="container">
                <div class="about-content">
                    <h2 class="section-title">About Us</h2>
                    <p>We're passionate about creating beautiful, functional websites that help your business grow.</p>
                </div>
            </div>
        </section>''',

            'portfolio': f'''        <section class="portfolio-section">
            <div class="container">
                <h2 class="section-title">Our Work</h2>
                <div class="portfolio-grid">
                    <div class="portfolio-item">
                        <div class="portfolio-overlay">
                            <h4>Project 1</h4>
                            <p>Web Design</p>
                        </div>
                    </div>
                    <div class="portfolio-item">
                        <div class="portfolio-overlay">
                            <h4>Project 2</h4>
                            <p>Mobile App</p>
                        </div>
                    </div>
                    <div class="portfolio-item">
                        <div class="portfolio-overlay">
                            <h4>Project 3</h4>
                            <p>Branding</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>''',

            'testimonials': f'''        <section class="testimonials-section">
            <div class="container">
                <h2 class="section-title">What People Say</h2>
                <div class="testimonials-grid">
                    <div class="testimonial-card">
                        <p>"Amazing service! They delivered beyond our expectations."</p>
                        <div class="testimonial-author">
                            <strong>- Sarah Johnson</strong>
                            <span>CEO, TechStart</span>
                        </div>
                    </div>
                    <div class="testimonial-card">
                        <p>"Highly recommended! Professional and creative team."</p>
                        <div class="testimonial-author">
                            <strong>- Michael Chen</strong>
                            <span>Founder, DesignLab</span>
                        </div>
                    </div>
                </div>
            </div>
        </section>''',

            'pricing': f'''        <section class="pricing-section">
            <div class="container">
                <h2 class="section-title">Pricing Plans</h2>
                <div class="pricing-grid">
                    <div class="pricing-card">
                        <h3>Starter</h3>
                        <p class="price">$29</p>
                        <ul>
                            <li>✓ Feature 1</li>
                            <li>✓ Feature 2</li>
                            <li>✓ Feature 3</li>
                        </ul>
                        <button class="btn btn-secondary">Get Started</button>
                    </div>
                    <div class="pricing-card featured">
                        <h3>Pro</h3>
                        <p class="price">$79</p>
                        <ul>
                            <li>✓ All Starter features</li>
                            <li>✓ Feature 4</li>
                            <li>✓ Feature 5</li>
                        </ul>
                        <button class="btn btn-primary">Get Started</button>
                    </div>
                </div>
            </div>
        </section>''',

            'contact': f'''        <section class="contact-section">
            <div class="container">
                <h2 class="section-title">Get in Touch</h2>
                <div class="contact-wrapper">
                    <form class="contact-form">
                        <div class="form-group">
                            <input type="text" placeholder="Your Name" required>
                        </div>
                        <div class="form-group">
                            <input type="email" placeholder="Your Email" required>
                        </div>
                        <div class="form-group">
                            <textarea placeholder="Your Message" rows="5" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Message</button>
                    </form>
                </div>
            </div>
        </section>''',

            'footer': f'''        <footer class="footer">
            <div class="container">
                <div class="footer-content">
                    <p>&copy; 2024 Your Company. All rights reserved.</p>
                    <div class="footer-links">
                        <a href="#privacy">Privacy</a>
                        <a href="#terms">Terms</a>
                        <a href="#contact">Contact</a>
                    </div>
                </div>
            </div>
        </footer>'''
        }

        return sections.get(section_type, '')

    @staticmethod
    def generate_css(palette: Dict) -> str:
        """Generate comprehensive CSS with proper containers"""
        css = f'''    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Playfair+Display:wght@400;500;600;700;800&display=swap');

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        :root {{
            --primary: {palette['primary']};
            --secondary: {palette['secondary']};
            --accent: {palette['accent']};
            --background: {palette['background']};
            --surface: {palette['surface']};
            --text-primary: {palette['text_primary']};
            --text-secondary: {palette['text_secondary']};
            --border: {palette['border']};
            --font-primary: 'Inter', sans-serif;
            --font-heading: 'Playfair Display', serif;
        }}

        body {{
            font-family: var(--font-primary);
            background: linear-gradient(135deg, var(--background) 0%, var(--surface) 100%);
            color: var(--text-primary);
            line-height: 1.6;
        }}

        /* Container for all sections */
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }}

        /* Section styling */
        section {{
            padding: 80px 0;
            position: relative;
        }}

        .section-title {{
            font-family: var(--font-heading);
            font-size: 2.5rem;
            text-align: center;
            margin-bottom: 50px;
            color: var(--text-primary);
            position: relative;
        }}

        .section-title::after {{
            content: '';
            position: absolute;
            bottom: -15px;
            left: 50%;
            transform: translateX(-50%);
            width: 80px;
            height: 4px;
            background: linear-gradient(90deg, var(--primary), var(--accent));
            border-radius: 2px;
        }}

        /* Header */
        header {{
            background: rgba(15, 23, 42, 0.95);
            backdrop-filter: blur(10px);
            padding: 1.5rem 0;
            position: sticky;
            top: 0;
            z-index: 100;
            border-bottom: 1px solid var(--border);
        }}

        header .container {{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}

        header h1 {{
            font-size: 1.8rem;
            font-weight: 700;
            background: linear-gradient(135deg, var(--primary), var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }}

        header nav a {{
            color: var(--text-secondary);
            text-decoration: none;
            margin-left: 2rem;
            transition: color 0.3s ease;
            font-weight: 500;
        }}

        header nav a:hover {{
            color: var(--primary);
        }}

        /* Hero Section */
        .hero-section {{
            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
            color: white;
            min-height: 600px;
            display: flex;
            align-items: center;
            text-align: center;
        }}

        .hero-content h1 {{
            font-size: 4rem;
            margin-bottom: 1rem;
            font-family: var(--font-heading);
            color: white;
        }}

        .hero-content p {{
            font-size: 1.35rem;
            margin-bottom: 2rem;
            color: rgba(255, 255, 255, 0.9);
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }}

        /* Buttons */
        .btn {{
            padding: 12px 30px;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            cursor: pointer;
            transition: all 0.3s ease;
            font-weight: 600;
            display: inline-block;
            text-decoration: none;
        }}

        .btn-primary {{
            background: var(--primary);
            color: white;
            box-shadow: 0 4px 15px rgba(0,0,0,0.3);
        }}

        .btn-primary:hover {{
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(0,0,0,0.4);
            background: var(--accent);
        }}

        .btn-secondary {{
            background: var(--secondary);
            color: white;
        }}

        .btn-secondary:hover {{
            background: var(--primary);
            transform: translateY(-2px);
        }}

        /* Features Section */
        .features-section {{
            background: var(--surface);
        }}

        .features-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }}

        .feature-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 40px 30px;
            border-radius: 16px;
            border: 1px solid var(--border);
            transition: all 0.3s ease;
            text-align: center;
            backdrop-filter: blur(10px);
        }}

        .feature-card:hover {{
            transform: translateY(-8px);
            border-color: var(--primary);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
        }}

        .feature-icon {{
            font-size: 3rem;
            margin-bottom: 20px;
        }}

        .feature-card h3 {{
            color: var(--primary);
            margin-bottom: 15px;
            font-size: 1.5rem;
        }}

        /* About Section */
        .about-section {{
            background: var(--background);
            text-align: center;
        }}

        .about-content {{
            max-width: 800px;
            margin: 0 auto;
            background: rgba(30, 41, 59, 0.5);
            padding: 50px;
            border-radius: 20px;
            border: 1px solid var(--border);
            backdrop-filter: blur(10px);
        }}

        .about-content p {{
            font-size: 1.2rem;
            color: var(--text-secondary);
            line-height: 1.8;
        }}

        /* Portfolio Section */
        .portfolio-section {{
            background: var(--surface);
        }}

        .portfolio-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
            gap: 30px;
        }}

        .portfolio-item {{
            aspect-ratio: 1;
            background: linear-gradient(135deg, var(--primary), var(--secondary));
            border-radius: 16px;
            position: relative;
            overflow: hidden;
            cursor: pointer;
            border: 1px solid var(--border);
        }}

        .portfolio-overlay {{
            position: absolute;
            bottom: -100%;
            left: 0;
            right: 0;
            background: rgba(0, 0, 0, 0.8);
            padding: 20px;
            transition: bottom 0.3s ease;
            text-align: center;
            backdrop-filter: blur(5px);
        }}

        .portfolio-item:hover .portfolio-overlay {{
            bottom: 0;
        }}

        .portfolio-overlay h4 {{
            color: white;
            margin-bottom: 5px;
            font-size: 1.2rem;
        }}

        .portfolio-overlay p {{
            color: rgba(255, 255, 255, 0.8);
            font-size: 0.9rem;
        }}

        /* Testimonials Section */
        .testimonials-section {{
            background: var(--background);
        }}

        .testimonials-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }}

        .testimonial-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 30px;
            border-left: 4px solid var(--primary);
            border-radius: 12px;
            backdrop-filter: blur(10px);
            border: 1px solid var(--border);
        }}

        .testimonial-card p {{
            font-style: italic;
            margin-bottom: 20px;
            color: var(--text-secondary);
            font-size: 1.1rem;
            line-height: 1.6;
        }}

        .testimonial-author {{
            display: flex;
            flex-direction: column;
        }}

        .testimonial-author strong {{
            color: var(--primary);
            font-size: 1rem;
        }}

        .testimonial-author span {{
            color: var(--text-secondary);
            font-size: 0.9rem;
        }}

        /* Pricing Section */
        .pricing-section {{
            background: var(--surface);
        }}

        .pricing-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 30px;
        }}

        .pricing-card {{
            background: rgba(30, 41, 59, 0.8);
            padding: 40px 30px;
            border-radius: 16px;
            border: 1px solid var(--border);
            text-align: center;
            transition: all 0.3s ease;
            backdrop-filter: blur(10px);
        }}

        .pricing-card.featured {{
            border-color: var(--primary);
            box-shadow: 0 20px 40px rgba(0,0,0,0.3);
            transform: scale(1.05);
        }}

        .pricing-card h3 {{
            font-size: 1.8rem;
            margin-bottom: 15px;
            color: var(--text-primary);
        }}

        .pricing-card .price {{
            font-size: 3rem;
            color: var(--primary);
            margin: 20px 0;
            font-weight: 700;
        }}

        .pricing-card ul {{
            list-style: none;
            margin: 30px 0;
            text-align: left;
        }}

        .pricing-card li {{
            padding: 10px 0;
            color: var(--text-secondary);
            border-bottom: 1px solid var(--border);
        }}

        .pricing-card li:last-child {{
            border-bottom: none;
        }}

        /* Contact Section */
        .contact-section {{
            background: var(--background);
        }}

        .contact-wrapper {{
            max-width: 600px;
            margin: 0 auto;
            background: rgba(30, 41, 59, 0.8);
            padding: 40px;
            border-radius: 20px;
            border: 1px solid var(--border);
            backdrop-filter: blur(10px);
        }}

        .contact-form {{
            display: flex;
            flex-direction: column;
            gap: 20px;
        }}

        .form-group input,
        .form-group textarea {{
            width: 100%;
            padding: 15px;
            border: 1px solid var(--border);
            border-radius: 8px;
            background: rgba(15, 23, 42, 0.8);
            color: var(--text-primary);
            font-family: var(--font-primary);
            font-size: 1rem;
        }}

        .form-group input:focus,
        .form-group textarea:focus {{
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(52,152,219,0.2);
        }}

        .form-group input::placeholder,
        .form-group textarea::placeholder {{
            color: var(--text-secondary);
            opacity: 0.7;
        }}

        /* Footer */
        .footer {{
            background: rgba(15, 23, 42, 0.95);
            border-top: 1px solid var(--border);
            padding: 40px 0;
        }}

        .footer-content {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 20px;
        }}

        .footer-links {{
            display: flex;
            gap: 30px;
        }}

        .footer-links a {{
            color: var(--text-secondary);
            text-decoration: none;
            transition: color 0.3s ease;
        }}

        .footer-links a:hover {{
            color: var(--primary);
        }}

        /* Responsive */
        @media (max-width: 768px) {{
            header .container {{
                flex-direction: column;
                gap: 15px;
            }}

            header nav a {{
                margin: 0 10px;
            }}

            .hero-content h1 {{
                font-size: 2.5rem;
            }}

            .section-title {{
                font-size: 2rem;
            }}

            .pricing-card.featured {{
                transform: scale(1);
            }}

            .footer-content {{
                flex-direction: column;
                text-align: center;
            }}

            .footer-links {{
                justify-content: center;
            }}
        }}
    </style>'''
        return css

class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, str]:
        """Generate complete HTML page"""

        # Generate color palette
        palette = ColorPaletteGenerator.generate_palette(style)

        # Extract sections
        sections = HTMLPageBuilder.extract_sections(description)

        # Generate meta tags
        meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)

        # Generate sections
        sections_html = '\n\n'.join([
            HTMLPageBuilder.generate_section_html(section, palette)
            for section in sections
            if HTMLPageBuilder.generate_section_html(section, palette)
        ])

        # Generate CSS
        css = HTMLPageBuilder.generate_css(palette)

        # Build complete HTML
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{meta_tags}
{css}
</head>
<body>
    <header>
        <div class="container">
            <h1>{title}</h1>
            <nav>
                <a href="#features">Features</a>
                <a href="#about">About</a>
                <a href="#contact">Contact</a>
            </nav>
        </div>
    </header>

    <main>
{sections_html}
    </main>
</body>
</html>'''

        return html, palette

generation_history = []

def generate_html_page(title: str, description: str, style: str = "modern") -> Tuple[str, str, str]:
    """Generate HTML page with styling"""
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""

    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)

        # Get color preview HTML
        color_preview_html = ColorPaletteGenerator.get_color_preview_html(palette)

        return html_output, "✅ HTML page generated successfully!", color_preview_html
    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_suggestions(style: str) -> str:
    """Get color suggestions based on style with visual preview"""
    palette = ColorPaletteGenerator.generate_palette(style)

    # Get color preview HTML
    color_preview_html = ColorPaletteGenerator.get_color_preview_html(palette)

    return color_preview_html

# Template functions
def load_portfolio():
    return ("Portfolio Website",
           "Hero section with welcome banner, portfolio gallery with 6 items, about section, testimonials, contact form, footer",
           "modern")

def load_saas():
    return ("SaaS Product",
           "Hero banner, features showcase with 3 items, pricing plans comparison, testimonials, call-to-action button, footer",
           "vibrant")

def load_company():
    return ("Company Website",
           "Header with navigation, hero section, about company, services list, team members, contact form, footer",
           "ocean")

def load_ecommerce():
    return ("E-Commerce Store",
           "Hero banner with sale, product grid with 4 items, featured categories, shopping features, newsletter signup, footer",
           "luxury")

def load_blog():
    return ("Personal Blog",
           "Hero with author intro, blog posts grid with 3 articles, categories sidebar, popular posts, newsletter, footer",
           "creative")

def load_restaurant():
    return ("Restaurant Website",
           "Hero with food image, menu section with specials, about chef, reservation form, customer reviews, location map, footer",
           "sunset")

def load_agency():
    return ("Creative Agency",
           "Hero with video background, services offered, case studies gallery, team members, client logos, contact section, footer",
           "creative")

def load_app_landing():
    return ("App Landing Page",
           "Hero with app screenshot, features with icons, how it works steps, download buttons, user reviews, FAQ, footer",
           "vibrant")

def load_fitness():
    return ("Fitness Center",
           "Hero with class schedule, trainer profiles, membership plans, facility gallery, client transformations, contact, footer",
           "forest")

print("🚀 Loading HTML Quick-Styler...")

# Custom CSS for Gradio interface
gradio_css = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');

/* Global Styles */
.gradio-container, .gradio-container * {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif !important;
}

/* Tab Styling */
.tabs {
    border: none !important;
    background: transparent !important;
}

.tab-nav {
    display: flex !important;
    gap: 4px !important;
    border-bottom: 1px solid #334155 !important;
    padding-bottom: 8px !important;
    margin-bottom: 20px !important;
}

.tab-nav button {
    background: transparent !important;
    border: none !important;
    padding: 10px 20px !important;
    color: #94a3b8 !important;
    font-weight: 500 !important;
    font-size: 14px !important;
    border-radius: 8px !important;
    transition: all 0.2s ease !important;
}

.tab-nav button:hover {
    background: #1e293b !important;
    color: #f1f5f9 !important;
}

.tab-nav button.selected {
    background: #2d3a4f !important;
    color: #fff !important;
    font-weight: 600 !important;
}

/* Container Styling */
.gr-box, .gr-form, .gr-panel {
    border: 1px solid #334155 !important;
    border-radius: 12px !important;
    background: #1a1a2e !important;
    padding: 20px !important;
    box-shadow: 0 4px 20px rgba(0,0,0,0.2) !important;
}

/* Input Fields */
input, textarea, select, .gr-input, .gr-dropdown {
    background: #0f172a !important;
    border: 1px solid #334155 !important;
    border-radius: 8px !important;
    color: #f1f5f9 !important;
    padding: 12px !important;
    font-size: 14px !important;
    transition: all 0.2s ease !important;
}

input:focus, textarea:focus, select:focus {
    border-color: #3498db !important;
    box-shadow: 0 0 0 2px rgba(52,152,219,0.2) !important;
    outline: none !important;
}

/* Labels */
label {
    font-size: 12px !important;
    font-weight: 600 !important;
    color: #94a3b8 !important;
    text-transform: uppercase !important;
    letter-spacing: 0.3px !important;
    margin-bottom: 6px !important;
}

/* Buttons */
.gr-button, button {
    border-radius: 8px !important;
    font-weight: 600 !important;
    font-size: 14px !important;
    padding: 10px 20px !important;
    transition: all 0.2s ease !important;
    border: none !important;
    cursor: pointer !important;
}

.gr-button-primary {
    background: #3498db !important;
    color: white !important;
}

.gr-button-primary:hover {
    background: #2980b9 !important;
    transform: translateY(-1px) !important;
    box-shadow: 0 4px 12px rgba(52,152,219,0.3) !important;
}

.gr-button-secondary {
    background: #2d3a4f !important;
    color: #f1f5f9 !important;
}

.gr-button-secondary:hover {
    background: #3a4a63 !important;
}

/* Template Cards */
.template-grid {
    display: grid !important;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)) !important;
    gap: 16px !important;
    margin: 20px 0 !important;
}

.template-card {
    background: #1e1e32 !important;
    border: 1px solid #2d3a4f !important;
    border-radius: 12px !important;
    padding: 20px !important;
    transition: all 0.2s ease !important;
    height: 100% !important;
    display: flex !important;
    flex-direction: column !important;
}

.template-card:hover {
    border-color: #3498db !important;
    transform: translateY(-2px) !important;
    box-shadow: 0 8px 24px rgba(0,0,0,0.3) !important;
}

.template-card h4 {
    color: #f1f5f9 !important;
    font-size: 16px !important;
    font-weight: 600 !important;
    margin-bottom: 8px !important;
}

.template-card p {
    color: #94a3b8 !important;
    font-size: 13px !important;
    margin-bottom: 16px !important;
    flex-grow: 1 !important;
    line-height: 1.5 !important;
}

.template-card .gr-button {
    margin-top: auto !important;
    background: #2d3a4f !important;
    color: #f1f5f9 !important;
    font-size: 12px !important;
    padding: 8px !important;
}

.template-card .gr-button:hover {
    background: #3498db !important;
}
"""

with gr.Blocks(title="HTML Quick-Styler", css=gradio_css) as demo:

    gr.Markdown("""
    # 🎨 HTML Quick-Styler
    Generate professional HTML pages with automatic styling
    """)

    with gr.Tabs():

        # ============= TAB 1: Generator =============
        with gr.TabItem("Generator"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### Page Details")

                    page_title = gr.Textbox(
                        label="Title",
                        value="Modern Portfolio Website",
                        lines=1
                    )

                    page_description = gr.Textbox(
                        label="Description",
                        value="Hero section with welcome message, features list with 3 items, about section, portfolio gallery, testimonials, contact form, and footer",
                        lines=4
                    )

                    color_style = gr.Dropdown(
                        ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                        value="modern",
                        label="Color Style"
                    )

                    generate_btn = gr.Button("Generate HTML", size="lg", variant="primary")

                with gr.Column(scale=1):
                    gr.Markdown("### Output")

                    html_output = gr.Code(
                        language="html",
                        label="HTML Code",
                        lines=20
                    )

                    status_msg = gr.Markdown()
                    color_info = gr.HTML()

            generate_btn.click(
                generate_html_page,
                inputs=[page_title, page_description, color_style],
                outputs=[html_output, status_msg, color_info]
            )

        # ============= TAB 2: Preview =============
        with gr.TabItem("Preview"):
            gr.Markdown("### Live Preview")

            with gr.Row():
                preview_button = gr.Button("Load Preview", size="lg", variant="primary")
                refresh_preview = gr.Button("Refresh", size="lg", variant="secondary")

            preview_output = gr.HTML(value="<p style='text-align:center; color:#fff; padding:40px;'>No preview loaded</p>")

            def show_preview(html_text):
                if not html_text or not html_text.strip():
                    return "<p style='text-align:center; color:#fff; padding:40px;'>No HTML provided</p>"
                return html_text

            preview_button.click(
                show_preview,
                inputs=[html_output],
                outputs=[preview_output]
            )

            refresh_preview.click(
                show_preview,
                inputs=[html_output],
                outputs=[preview_output]
            )

        # ============= TAB 3: Colors =============
        with gr.TabItem("Colors"):
            gr.Markdown("### Color Palettes")

            with gr.Row():
                style_selector = gr.Dropdown(
                    ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                    value="modern",
                    label="Select Style",
                    interactive=True
                )

                palette_btn = gr.Button("Show Colors", size="lg", variant="primary")

            palette_display = gr.HTML()

            palette_btn.click(
                get_color_suggestions,
                inputs=[style_selector],
                outputs=[palette_display]
            )

        # ============= TAB 4: Templates =============
        with gr.TabItem("Templates"):
            gr.Markdown("### Quick Templates")

            # Basic Templates
            gr.Markdown("#### Basic")
            with gr.Row(elem_classes="template-grid"):
                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**📸 Portfolio**")
                        gr.Markdown("*Hero, Gallery, About, Contact*")
                        portfolio_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**🚀 SaaS**")
                        gr.Markdown("*Hero, Features, Pricing, CTA*")
                        saas_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**🏢 Company**")
                        gr.Markdown("*Hero, Services, Team, Contact*")
                        company_btn = gr.Button("Use Template", size="sm", variant="secondary")

            # E-Commerce & Blog
            gr.Markdown("#### E-Commerce & Blog")
            with gr.Row(elem_classes="template-grid"):
                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**🛒 Store**")
                        gr.Markdown("*Hero, Products, Categories*")
                        ecommerce_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**📝 Blog**")
                        gr.Markdown("*Author, Posts, Categories*")
                        blog_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**🍽️ Restaurant**")
                        gr.Markdown("*Menu, Chef, Reservations*")
                        restaurant_btn = gr.Button("Use Template", size="sm", variant="secondary")

            # Creative & App
            gr.Markdown("#### Creative & App")
            with gr.Row(elem_classes="template-grid"):
                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**🎪 Agency**")
                        gr.Markdown("*Hero, Services, Case Studies*")
                        agency_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**📱 App**")
                        gr.Markdown("*Screenshot, Features, Download*")
                        app_btn = gr.Button("Use Template", size="sm", variant="secondary")

                with gr.Column():
                    with gr.Group(elem_classes="template-card"):
                        gr.Markdown("**💪 Fitness**")
                        gr.Markdown("*Schedule, Trainers, Plans*")
                        fitness_btn = gr.Button("Use Template", size="sm", variant="secondary")

            # Connect template buttons
            portfolio_btn.click(load_portfolio, outputs=[page_title, page_description, color_style])
            saas_btn.click(load_saas, outputs=[page_title, page_description, color_style])
            company_btn.click(load_company, outputs=[page_title, page_description, color_style])
            ecommerce_btn.click(load_ecommerce, outputs=[page_title, page_description, color_style])
            blog_btn.click(load_blog, outputs=[page_title, page_description, color_style])
            restaurant_btn.click(load_restaurant, outputs=[page_title, page_description, color_style])
            agency_btn.click(load_agency, outputs=[page_title, page_description, color_style])
            app_btn.click(load_app_landing, outputs=[page_title, page_description, color_style])
            fitness_btn.click(load_fitness, outputs=[page_title, page_description, color_style])

        # ============= TAB 5: Guide =============
        with gr.TabItem("Guide"):
            gr.Markdown("""
            # Quick Guide

            ## How to Use
            1. **Generator** - Enter title and description
            2. **Preview** - See your page live
            3. **Colors** - Browse color schemes
            4. **Templates** - Start with pre-built layouts

            ## Keywords
            - hero, banner → Hero Section
            - features, services → Features Grid
            - about, team → About Section
            - portfolio, gallery → Portfolio
            - testimonials, reviews → Testimonials
            - pricing, plans → Pricing Plans
            - contact, form → Contact Form
            - footer → Footer

            ## Color Styles
            - **Modern** - Professional blues
            - **Vibrant** - Bold greens
            - **Ocean** - Calm blues
            - **Forest** - Natural greens
            - **Sunset** - Warm oranges
            - **Luxury** - Elegant gold/black
            - **Creative** - Purple gradients
            - **Minimal** - Clean grays
            """)

print("\n✅ HTML Quick-Styler Ready!\n")
demo.launch(share=True, show_error=True, debug=False)