# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8u2_KFxO5EPUGGZeFLbt2TNllXFs4dd
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random

class ColorPaletteGenerator:
    """Generate visually cohesive color palettes"""

    @staticmethod
    def generate_palette(style: str = "modern") -> Dict[str, str]:
        """Generate a cohesive color palette based on style"""

        palettes = {
            'modern': {
                'primary': '#667eea',
                'secondary': '#764ba2',
                'accent': '#f093fb',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'vibrant': {
                'primary': '#ff6b6b',
                'secondary': '#ff8e72',
                'accent': '#f5576c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'ocean': {
                'primary': '#0099cc',
                'secondary': '#006699',
                'accent': '#00ccff',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'forest': {
                'primary': '#27ae60',
                'secondary': '#1e8449',
                'accent': '#52be80',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'sunset': {
                'primary': '#ff8c42',
                'secondary': '#ff6b35',
                'accent': '#ffa751',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'luxury': {
                'primary': '#1a1a1a',
                'secondary': '#333333',
                'accent': '#FFD700',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'creative': {
                'primary': '#9b59b6',
                'secondary': '#8e44ad',
                'accent': '#e74c3c',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            },
            'minimal': {
                'primary': '#2c3e50',
                'secondary': '#34495e',
                'accent': '#3498db',
                'background': '#0f172a',
                'surface': '#1e293b',
                'text_primary': '#f1f5f9',
                'text_secondary': '#cbd5e1',
                'border': '#334155'
            }
        }

        return palettes.get(style.lower(), palettes['modern'])

class HTMLPageBuilder:
    """Build styled HTML pages from descriptions"""

    @staticmethod
    def extract_sections(description: str) -> List[str]:
        """Extract sections from description"""
        sections = []

        section_keywords = {
            'hero': ['hero', 'banner', 'landing'],
            'features': ['features', 'services', 'benefits'],
            'about': ['about', 'team', 'company'],
            'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
            'testimonials': ['testimonial', 'reviews', 'feedback'],
            'pricing': ['pricing', 'plans', 'cost'],
            'contact': ['contact', 'form', 'reach'],
            'footer': ['footer', 'bottom']
        }

        desc_lower = description.lower()

        for section_type, keywords in section_keywords.items():
            for keyword in keywords:
                if keyword in desc_lower:
                    sections.append(section_type)
                    break

        if not sections:
            sections = ['hero', 'features', 'contact', 'footer']

        return sections

 @staticmethod
def generate_section_html(section_type: str, palette: Dict) -> str:
    """Generate HTML for sections with images and better content"""

    sections = {

        "hero": """
<section class="hero">
<div class="hero-overlay"></div>

<div class="hero-content">
<h1>Build Stunning Digital Experiences</h1>
<p>Modern websites, powerful applications and beautiful user experiences.</p>
<button class="btn btn-primary">Explore Our Work</button>
</div>

</section>
""",

        "features": """
<section class="features">

<h2>Our Services</h2>

<div class="features-grid">

<div class="feature-card">
<h3>Web Development</h3>
<p>High-performance responsive websites using modern technologies.</p>
</div>

<div class="feature-card">
<h3>UI / UX Design</h3>
<p>Clean user interfaces designed for engagement and usability.</p>
</div>

<div class="feature-card">
<h3>Performance Optimization</h3>
<p>Fast optimized websites for better SEO and user experience.</p>
</div>

</div>

</section>
""",

        "about": """
<section class="about">

<img class="about-image"
src="https://images.unsplash.com/photo-1552664730-d307ca884978">

<div class="about-content">
<h2>About Our Team</h2>
<p>
We are a creative digital studio focused on building
beautiful websites and modern web applications.
Our mission is to help brands grow through design
and technology.
</p>
</div>

</section>
""",

        "portfolio": """
<section class="portfolio">

<h2>Our Work</h2>

<div class="portfolio-grid">

<div class="portfolio-item">

<img src="https://images.unsplash.com/photo-1559028012-481c04fa702d">

<div class="portfolio-info">
<h3>Startup Website</h3>
<p>Modern responsive website designed for a growing startup brand.</p>
<button class="btn btn-primary">View Project</button>
</div>

</div>

<div class="portfolio-item">

<img src="https://images.unsplash.com/photo-1498050108023-c5249f4df085">

<div class="portfolio-info">
<h3>SaaS Dashboard</h3>
<p>Clean admin dashboard with analytics and reporting tools.</p>
<button class="btn btn-primary">View Project</button>
</div>

</div>

<div class="portfolio-item">

<img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d">

<div class="portfolio-info">
<h3>Business Platform</h3>
<p>Digital platform for managing business workflows and customers.</p>
<button class="btn btn-primary">View Project</button>
</div>

</div>

</div>

</section>
""",

        "testimonials": """
<section class="testimonials">

<h2>Client Testimonials</h2>

<div class="testimonials-grid">

<div class="testimonial">
<p>"Amazing service and fantastic design work."</p>
<span>- Startup Founder</span>
</div>

<div class="testimonial">
<p>"Professional team with excellent attention to detail."</p>
<span>- Product Manager</span>
</div>

</div>

</section>
""",

        "contact": """
<section class="contact">

<img class="contact-image"
src="https://images.unsplash.com/photo-1522071820081-009f0129c71c">

<h2>Get in Touch</h2>

<form class="contact-form">

<input type="text" placeholder="Your Name" required>

<input type="email" placeholder="Your Email" required>

<textarea rows="5" placeholder="Tell us about your project"></textarea>

<button type="submit" class="btn btn-primary">
Send Message
</button>

</form>

</section>
""",

        "footer": """
<footer class="footer">

<div class="footer-content">

<p>© 2024 Your Company. All rights reserved.</p>

<div class="footer-links">
<a href="#">Privacy</a>
<a href="#">Terms</a>
<a href="#">Contact</a>
</div>

</div>

</footer>
"""
    }

    return sections.get(section_type, "")
@staticmethod
def generate_css(palette: Dict) -> str:

    css = f"""
<style>

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Poppins:wght@500;600;700&display=swap');

* {{
margin:0;
padding:0;
box-sizing:border-box;
}}

body {{
font-family:'Inter',sans-serif;
background:white;
color:{palette['text_primary']};
line-height:1.6;
}}

main {{
max-width:1200px;
margin:auto;
padding:40px 20px;
}}

section {{
margin:100px 0;
}}

h1,h2,h3 {{
font-family:'Poppins',timesnewroman;
}}

h2 {{
text-align:center;
margin-bottom:40px;
}}

.hero {{
position:relative;
height:550px;
display:flex;
align-items:center;
justify-content:center;
text-align:center;
background-image:url("https://images.unsplash.com/photo-1555066931-4365d14bab8c");
background-size:cover;
background-position:center;
}}

.hero-overlay {{
position:absolute;
inset:0;
background:rgba(0,0,0,0.65);
}}

.hero-content {{
position:relative;
z-index:2;
}}

.hero h1 {{
font-size:3.5rem;
margin-bottom:20px;
}}

.hero p {{
font-size:1.3rem;
margin-bottom:25px;
}}

.btn {{
padding:14px 28px;
border:none;
border-radius:10px;
cursor:pointer;
}}

.btn-primary {{
background:{palette['primary']};
color:white;
}}

.features-grid {{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(260px,1fr));
gap:30px;
}}

.feature-card {{
background:{palette['surface']};
padding:30px;
border-radius:12px;
border:1px solid {palette['border']};
}}

.portfolio-grid {{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(280px,1fr));
gap:30px;
}}

.portfolio-item img {{
width:100%;
height:250px;
object-fit:cover;
border-radius:12px;
}}
.portfolio-item{{
background:{palette['surface']};
border-radius:12px;
overflow:hidden;
border:1px solid {palette['border']};
transition:0.3s;
}}

.portfolio-item:hover{{
transform:translateY(-6px);
}}

.portfolio-info{{
padding:20px;
}}

.portfolio-info h3{{
margin-bottom:10px;
}}

.portfolio-info p{{
color:{palette['text_secondary']};
margin-bottom:15px;
}}
.about {{
display:flex;
gap:40px;
align-items:center;
}}

.about-image {{
width:50%;
border-radius:12px;
}}

.testimonials-grid {{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(280px,1fr));
gap:30px;
}}

.testimonial {{
background:{palette['surface']};
padding:25px;
border-left:4px solid {palette['primary']};
border-radius:8px;
}}

.contact-image {{
width:100%;
border-radius:12px;
margin-bottom:30px;
}}

.contact-form {{
display:flex;
flex-direction:column;
gap:20px;
}}

.contact-form input,
.contact-form textarea {{
padding:12px;
border-radius:8px;
border:1px solid {palette['border']};
background:{palette['surface']};
color:white;
}}

.footer {{
margin-top:100px;
border-top:1px solid {palette['border']};
padding:40px;
}}

.footer-content {{
display:flex;
justify-content:space-between;
max-width:1200px;
margin:auto;
}}

.footer-links a {{
margin-left:20px;
color:{palette['text_secondary']};
text-decoration:none;
}}

</style>
"""
    return css
class HTMLGenerationEngine:
    """Main engine for HTML page generation"""

    @staticmethod
    def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, str]:
        """Generate complete HTML page"""

        # Generate color palette
        palette = ColorPaletteGenerator.generate_palette(style)

        # Extract sections
        sections = HTMLPageBuilder.extract_sections(description)

        # Generate meta tags
        meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)

        # Generate sections
        sections_html = '\n\n'.join([
            HTMLPageBuilder.generate_section_html(section, palette)
            for section in sections
            if HTMLPageBuilder.generate_section_html(section, palette)
        ])

        # Generate CSS
        css = HTMLPageBuilder.generate_css(palette)

        # Build complete HTML
        html = f'''<!DOCTYPE html>
<html lang="en">
<head>
{meta_tags}
{css}
</head>
<body>
    <header>
        <nav>
            <h1>{title}</h1>
            <div>
                <a href="#features">Features</a>
                <a href="#about">About</a>
                <a href="#contact">Contact</a>
            </div>
        </nav>
    </header>

    <main>
{sections_html}
    </main>
</body>
</html>'''

        return html, palette

generation_history = []

def generate_html_page(title: str, description: str, style: str = "modern") -> Tuple[str, str, str]:
    """Generate HTML page with styling"""
    if not title.strip() or not description.strip():
        return "", "❌ Please provide both title and description!", ""

    try:
        html_output, palette = HTMLGenerationEngine.generate_page(title, description, style)

        color_info = f"""
**Color Palette:**
- Primary: {palette['primary']}
- Secondary: {palette['secondary']}
- Accent: {palette['accent']}
- Background: {palette['background']}
"""

        generation_history.append({
            'title': title,
            'description': description,
            'html': html_output,
            'palette': palette,
            'timestamp': datetime.now().isoformat()
        })

        return html_output, "✅ HTML page generated successfully!", color_info
    except Exception as e:
        return "", f"❌ Error: {str(e)}", ""

def get_color_suggestions(style: str) -> str:
    """Get color suggestions based on style"""
    palette = ColorPaletteGenerator.generate_palette(style)

    palette_text = f"""
**Palette for "{style}" style:**
- Primary: {palette['primary']}
- Secondary: {palette['secondary']}
- Accent: {palette['accent']}
- Background: {palette['background']}
- Text: {palette['text_primary']}
"""
    return palette_text

print("🚀 Loading HTML Quick-Styler Advanced...")

with gr.Blocks(title="HTML Quick-Styler - Advanced Edition") as demo:

    gr.Markdown("""
    # 🎨 HTML Quick-Styler Advanced
    ## Professional HTML Page Generator with Auto-Styling

    **Generate production-ready HTML pages in seconds**
    """)

    with gr.Tabs():

        # ============= TAB 1: Page Generator =============
        with gr.TabItem("🎯 Generate Page"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📝 Page Details")

                    page_title = gr.Textbox(
                        label="Page Title",
                        value="Modern Portfolio Website",
                        lines=1
                    )

                    page_description = gr.Textbox(
                        label="Page Description & Sections",
                        value="Hero section with welcome message, features list with 3 items, about section, portfolio gallery, testimonials, contact form, and footer",
                        lines=4
                    )

                    color_style = gr.Dropdown(
                        ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                        value="modern",
                        label="🎨 Color Style"
                    )

                    generate_btn = gr.Button("✨ Generate HTML", size="lg", variant="primary")

                with gr.Column(scale=1):
                    gr.Markdown("### 📊 Output")

                    html_output = gr.Code(
                        language="html",
                        label="Generated HTML/CSS",
                        lines=20
                    )

                    status_msg = gr.Markdown()
                    color_info = gr.Markdown()

            generate_btn.click(
                generate_html_page,
                inputs=[page_title, page_description, color_style],
                outputs=[html_output, status_msg, color_info]
            )

        # ============= TAB 2: Preview =============
        with gr.TabItem("👁️ Live Preview"):
            gr.Markdown("### 🔍 Preview Generated Page")

            preview_button = gr.Button("🔄 Load Preview", size="lg", variant="primary")
            preview_output = gr.HTML(value="<p style='text-align:center; color:#fff; padding:40px;'>No preview loaded. Generate a page first.</p>")

            def show_preview(html_text):
                if not html_text.strip():
                    return "<p style='text-align:center; color:#fff; padding:40px;'>No HTML provided</p>"
                return html_text

            preview_button.click(
                show_preview,
                inputs=[html_output],
                outputs=[preview_output]
            )

        # ============= TAB 3: Color Palettes =============
        with gr.TabItem("🎨 Color Palettes"):
            gr.Markdown("### 🌈 Explore Color Schemes")

            with gr.Row():
                style_selector = gr.Radio(
                    ["modern", "vibrant", "ocean", "forest", "sunset", "luxury", "creative", "minimal"],
                    value="modern",
                    label="Choose Style"
                )

                palette_btn = gr.Button("🎨 Get Palette", size="lg", variant="primary")

            palette_display = gr.Markdown()

            palette_btn.click(
                get_color_suggestions,
                inputs=[style_selector],
                outputs=[palette_display]
            )

        # ============= TAB 4: Templates =============
        with gr.TabItem("📋 Templates"):
            gr.Markdown("### 📝 Quick Templates")

            with gr.Row():
                with gr.Column():
                    gr.Markdown("""
                    #### Portfolio Website
                    Hero, Portfolio Gallery, About, Contact, Footer
                    """)
                    portfolio_btn = gr.Button("Use Template", size="sm")

                    def load_portfolio():
                        return ("Portfolio Website",
                               "Hero section with welcome banner, portfolio gallery with 6 items, about section, testimonials, contact form, footer",
                               "modern")

                    portfolio_btn.click(load_portfolio, outputs=[page_title, page_description, color_style])

                with gr.Column():
                    gr.Markdown("""
                    #### SaaS Landing Page
                    Hero, Features, Pricing, Testimonials, CTA, Footer
                    """)
                    saas_btn = gr.Button("Use Template", size="sm")

                    def load_saas():
                        return ("SaaS Product",
                               "Hero banner, features showcase with 3 items, pricing plans comparison, testimonials, call-to-action button, footer",
                               "vibrant")

                    saas_btn.click(load_saas, outputs=[page_title, page_description, color_style])

                with gr.Column():
                    gr.Markdown("""
                    #### Company Website
                    Header, About, Services, Team, Contact, Footer
                    """)
                    company_btn = gr.Button("Use Template", size="sm")

                    def load_company():
                        return ("Company",
                               "Header with navigation, hero section, about company, services list, team members, contact form, footer",
                               "ocean")

                    company_btn.click(load_company, outputs=[page_title, page_description, color_style])

        # ============= TAB 5: Guide =============
        with gr.TabItem("📚 Guide"):
            gr.Markdown("""
            # 📖 HTML Quick-Styler Guide

            ## How It Works

            ### 1. Enter Details
            - **Title:** Page name
            - **Description:** Sections you want
            - **Color Style:** Pick a theme

            ### 2. Automatic Detection
            The tool recognizes these keywords:
            - `hero` / `banner` → Hero Section
            - `features` / `services` → Features Grid
            - `about` / `team` → About Section
            - `portfolio` / `gallery` → Portfolio
            - `testimonial` / `reviews` → Testimonials
            - `pricing` / `plans` → Pricing Plans
            - `contact` / `form` → Contact Form
            - `footer` → Footer

            ### 3. Generate & Customize
            - Copy generated HTML
            - Edit text and colors
            - Save as .html file
            - Open in browser

            ## Features
            ✅ Responsive design
            ✅ Modern animations
            ✅ SEO meta tags
            ✅ Professional styling
            ✅ Dark theme
            ✅ Color palettes
            ✅ Copy-paste ready

            ## Color Styles
            - **Modern:** Professional blues
            - **Vibrant:** Bold reds
            - **Ocean:** Calm blues
            - **Forest:** Natural greens
            - **Sunset:** Warm oranges
            - **Luxury:** Elegant blacks
            - **Creative:** Purple artistic
            - **Minimal:** Clean grays
            """)

print("\n✅ HTML Quick-Styler Advanced Ready!\n")
demo.launch(share=True, show_error=True, show_api=False)